module.exports = {
  apps: [
    {
      name: 'football-streaming',
      script: 'src/index.js',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      // Watch Node RSS only — Chromium is separate. Keep Node small on 1GB hosts.
      max_memory_restart: '350M',
      node_args: '--max-old-space-size=256 --expose-gc',
      // Prefer .env via dotenv in src/index.js; keep aligned defaults here for PM2.
      env: {
        NODE_ENV: 'production',
        TZ: 'Asia/Yangon',
        HOST: '0.0.0.0',
        PORT: 3000,
        LOW_MEMORY_MODE: 'true',
        USE_LOCAL_CONFIG: 'true',
        NODE_OPTIONS: '--max-old-space-size=256 --expose-gc',
        PUPPETEER_HEADLESS: 'new',
        PUPPETEER_TIMEOUT_MS: '45000',
        PUPPETEER_BLOCK_RESOURCES: 'true',
        PUPPETEER_MAX_PAGES: '2',
        PUPPETEER_CONCURRENCY: '1',
        SCRAPER_CONCURRENCY: '2',
        HTTP_STREAM_MAX_EMBEDS: '2',
        STREAM_SEARCH_INTERVAL_MINUTES: '5',
        STREAM_MAX_ATTEMPTS: '3',
        STREAM_POST_KICKOFF_MAX_MINUTES: '15',
        MATCH_URL_PRE_KICKOFF_MINUTES: '60,45,30',
        STREAM_EXTRACT_PRE_KICKOFF_MINUTES: '30,15,5',
        BROWSER_RESTART_EVERY_N_PAGES: '5',
        STREAM_FAST_HEALTH_TIMEOUT_MS: '8000',
        HIGHLIGHT_LIMIT: '8',
        MAX_STREAM_RETRIES: '1',
        MYANMARTV_CONCURRENCY: '1',
        PIPELINE_CRON: '*/5 * * * *',
        HIGHLIGHT_CRON: '0 */6 * * *',
        MYANMARTV_CRON: '*/8 * * * *',
        TIPS_CRON: '7 8,20 * * *',
        DOMAIN_CHECK_ENABLED: 'true',
        DOMAIN_CHECK_CRON: '0 * * * *',
      },
      error_file: 'logs/pm2-error.log',
      out_file: 'logs/pm2-out.log',
      merge_logs: true,
      time: true,
      kill_timeout: 15000,
      listen_timeout: 10000,
      autorestart: true,
      max_restarts: 30,
      restart_delay: 10000,
    },
  ],
};
